### PR TITLE
feat: add fail soft option to store valid temperature

### PR DESCRIPTION
**Pull request by narugit**
### About
- Add fail soft option (`-f`) to store valid temperature
- This option would be helpful with M2 Mac whose sensor is not stable (See also https://github.com/narugit/smctemp/issues/32)

### CODE REVIEW

**Comment by narugit** [comment]
Hi @kyleyannelli 
I've added fail soft option which I've described in https://github.com/narugit/smctemp/pull/34#issuecomment-2291332466
Could you try this branch on your PC?

**Comment by kyleyannelli** [comment]
```
╭─kyannelli::mbp @ ~/smctemp/narugit
╰─ » ./smctemp -c -n1000 -f                                                                                                                                                                    1 ↵
35.4
Time: 0h:00m:04s

╭─kyannelli::mbp @ ~/smctemp/narugit
╰─ » cat /tmp/smctemp/cpu_temperature.txt
35.3717
```
LGTM

**Comment by narugit** [comment]
@kyleyannelli 
Thank you for quick check!
But sorry, I've updated the code, so could you kindly test again?

**Comment by narugit** [comment]
@kyleyannelli 
Is smctemp work when you could not get valid temperature value?

```console
$ smctemp -c -n1000 -f

↓This would read last valid temperature from /tmp/ because it would fail to get valid temperature
$ smctemp -c -n1 -f 
```

**Comment by kyleyannelli** [comment]
@narugit Yes, it works. Thanks!

**Pull request merged**
